name: flutter_mm_hrmangement
description: A Flutter application for Mutual Mobile Employees for checking Calender and Leaves.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.2.5
  cloud_firestore: ^0.8.0
  firebase_messaging: ^2.0.0
  flutter_redux: ^0.5.2
  redux: ^3.0.0
  shared_preferences: ^0.4.2
  fluro: "^1.3.4"
  intl: "^0.15.7"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/login.jpg
    - assets/logo.jpg
    - assets/home.jpeg
    - assets/mutualmobile.png

    - assets/images/owl.png
    - assets/images/page1.webp
    - assets/images/page2.webp
    - assets/images/page3.webp
