name: flutter_mm_hrmangement
description: A Flutter application for Mutual Mobile Employees for checking Calender and Leaves.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.2.5
  cloud_firestore: ^0.8.0
  firebase_messaging: ^2.0.0
  flutter_redux: ^0.5.2
  redux: ^3.0.0
  shared_preferences: ^0.4.2
  fluro: "^1.3.4"
  intl: "^0.15.7"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/login.jpg
    - assets/page1.jpg
    - assets/page2.jpg
    - assets/page3.jpg
    - assets/home.jpeg
    - assets/tick.png
    - assets/mutualmobile.png
    - assets/reindeer.png

    - assets/images/owl.png
    - assets/images/book1.gif
    - assets/images/book2.gif
    - assets/images/book3.gif
    - assets/images/book4.gif

    - assets/images/frappe.png
    - assets/images/glass.png
    - assets/images/frappe_with_straw.png
    - assets/images/glass_with_straw.png
